travis:
  secure:
    BINSTAR_TOKEN: H1PGUs6gWL3uHfcx6ttvTn6PfYcrPBx6Phh41fapXLr95MtOTL8qMdoi2iMdezKvRfk9EXXkcAnZRq68fcuhaeeGutlh5dydsjfRirkZGh80m3X1RCa3ztJ5CQdBOxooksevsphYcj1xND6Ri2HSROCDCt+tgSjVr72kACgs+sih6f5iQrt2SlS4y+8N8fFUGzNRZ3rSgXIUnYcuX303Ac7i+oZqyIt94HIkR3awBYjD9BPRJ6JRPYEvMuBjkLB/rclXLsi9SJ6V7jn5p95sEWCV1TKP5D1nDUTctkgBDInnZVHcvTHrGAh1HV3dWECXDCNUtx/fm5JfQru2QrEqIQIy5sXT6k5RDAjJvARCKqIX7FusbJ41hLQdG6VlUvIuSy1+pronRSmHL7wkUPr1xOSX48UJwRX451Pe4/a2j8sFjzG7xXGNKD7/ZYwp2bECiQIKcL3lI21Kl4neDJ32b9uGeFu76Yzy7zImDHk+LDDxX+AkOmJBWzOoJM4oeyFJE3TZrVsXdJT2Gma1C6YqY5XAOzP4s918uPwGUlv8MCUroKXlxK5PCqCd1i45HHk2QTMgpECIX2IR9T0XWvfSSyyRxlZLCm3F5odRWlWH1xh1XWzqY5h4v+oE4IX2/AE4QxeTAAwhjrRcewmn2Socd65fBr3Zd92SG5FG+6c2omQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
